test:
  name: Ostronaut
  description: Поделитесь своими фотографиями с друзьями и близкими через Вконтакте и Facebook
  host: tripbrodev.ru:3000
  fb_app_id: ***REMOVED***
  fb_app_secret: ***REMOVED***
  aws_access: ***REMOVED***
  aws_secret: ***REMOVED***
  aws_bucket: ostronaut-dev
  fsq_key: ***REMOVED***
  fsq_secret: ***REMOVED***
  vk_app_id: ***REMOVED***
  vk_secret: ***REMOVED***
  vk_scopes: "friends,photos,status,wall,offline"
  contact_email: ***REMOVED***

development:
  name: Piclar Development
  description: Поделитесь своими фотографиями с друзьями и близкими через Вконтакте и Facebook
  host: piclardev.com:3000
  asset_host: tripbrodev.com:3000
  fb_app_id: 251326115000725
  fb_app_secret: ***REMOVED***
  aws_access: ***REMOVED***
  aws_secret: ***REMOVED***
  aws_bucket: ostronaut-dev
  aws_path: development
  fsq_key: ***REMOVED***
  fsq_secret: ***REMOVED***
  vk_app_id: ***REMOVED***
  vk_secret: ***REMOVED***
  vk_scopes: "friends,photos,status,wall,offline"
  s3_cdn: s3.amazonaws.com/piclar
  contact_email: ***REMOVED***

production:
  name: Piclar
  description: Поделитесь своими фотографиями с друзьями и близкими через Вконтакте и Facebook
  host: piclar.com
  asset_host: piclar.com
  fb_app_id: ***REMOVED***
  fb_app_secret: ***REMOVED***
  aws_access: ***REMOVED***
  aws_secret: ***REMOVED***
  aws_bucket: piclar
  aws_path: production
  fsq_key: ***REMOVED***
  fsq_secret: ***REMOVED***
  vk_app_id: ***REMOVED***
  vk_secret: ***REMOVED***
  vk_scopes: "friends,photos,status,wall,offline"
  s3_cdn: cdn.piclar.com
  contact_email: ***REMOVED***
