test:
  name: Ostronaut
  description: DICK
  host: tripbrodev.ru:3000
  fb_app_id: ***REMOVED***
  fb_app_secret: ***REMOVED***
  aws_access: ***REMOVED***
  aws_secret: ***REMOVED***
  aws_bucket: ostronaut-dev
  fsq_key: ***REMOVED***
  fsq_secret: ***REMOVED***
  vk_app_id: 3410309
  vk_secret: bh5DT17Gg8AYH6IPMr83
  vk_scopes: "friends,photos,status,wall,offline"
  contact_email: blah@blah.com

development:
  name: Piclar Development
  description: AWESUM
  host: piclardev.com:3000
  asset_host: tripbrodev.com:3000
  fb_app_id: 251326115000725
  fb_app_secret: ***REMOVED***
  aws_access: ***REMOVED***
  aws_secret: ***REMOVED***
  aws_bucket: ostronaut-dev
  aws_path: development
  fsq_key: ***REMOVED***
  fsq_secret: ***REMOVED***
  vk_app_id: 3410309
  vk_secret: bh5DT17Gg8AYH6IPMr83
  vk_scopes: "friends,photos,status,wall,offline"
  s3_cdn: s3.amazonaws.com/piclar
  contact_email: blah@blah.com

production:
  name: Piclar
  description: INSERT DESCRIPTION
  host: piclar.com
  asset_host: piclar.com
  fb_app_id: ***REMOVED***
  fb_app_secret: ***REMOVED***
  aws_access: ***REMOVED***
  aws_secret: ***REMOVED***
  aws_bucket: piclar
  aws_path: production
  fsq_key: ***REMOVED***
  fsq_secret: ***REMOVED***
  vk_app_id: 3410309
  vk_secret: bh5DT17Gg8AYH6IPMr83
  vk_scopes: "friends,photos,status,wall,offline"
  s3_cdn: cdn.piclar.com
  contact_email: blah@blah.com
