default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: piclar_development
  pool: 25
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: piclar_development

test:
  <<: *default
  database: piclar_test

production:
  <<: *default
  database: piclar_production
  username: master
  password: stanf0rd
  host: linksie.cvlxmdsey5id.eu-west-1.rds.amazonaws.com

