default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ostronaut_development
  pool: 25
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: ostronaut_development

test:
  <<: *default
  database: ostronaut_test

production:
  <<: *default
  database: ostronaut_production
  username: master
  password: stanf0rd
  host: linksie.csk3baxbq9se.us-east-1.rds.amazonaws.com
